const menu = [{
        title: "slow roasted beef",
        sectionId: "beef",
        products: [{
                name: "Classic Roast Beef",
                subTitle: false,
                slug: "classic-roast-beef",
                calories: 306,
                description: "Este es el sándwich que puso al Roast Beef en el mapa. Nuestro clásico Roast Beef se corta en finas rodajas y se coloca en un pan con semillas de ajonjolí tostado. Pruébalo con nuestra deliciosa Arby's Sauce®, o para darle un toque extra con la sabrosa Horsey Sauce.",
                calories_description: "306 Calorías | Combo 811-1171",
                type: false,
                image: require("~/assets/images/classic-roast-beef.jpg"),
            },
            {
                name: "DOUBLE ROAST BEEF",
                subTitle: false,
                slug: "double-roast-beef",
                calories: 506,
                description: "Este sándwich tiene dos veces la cantidad de nuestro famoso Classic Roast Beef. Perfecto para esos momentos en los que tienes el doble de hambre o simplemente se te antoja más roast beef en tu sándwich.",
                calories_description: "506 Calorías | 960-1320 Combo",
                type: 2,
                image: require("~/assets/images/double-roast-beef.jpg"),
            },
            {
                name: "HALF POUND ROAST BEEF",
                subTitle: false,
                slug: "half-pound-roast-beef",
                calories: 610,
                description: "Permítenos presentarte a nuestro sándwich de Roast Beef más grande, el Half Pound Roast Beef, un día nos pusimos a agregar más de nuestro exclusivo Roast Beef hasta que el pan de abajo apenas pudo soportarlo.",
                calories_description: "610 Calorías | 1060-1420 Combo",
                type: 3,
                image: require("~/assets/images/half-pound-roast-beef.jpg"),
            },
            {
                name: "Classic Beef & Cheddar",
                subTitle: false,
                slug: "classic-beef-n-cheddar",
                calories: 450,
                description: "Hubo quien pensó que no había forma que el sándwich de Roast Beef de Arby's pudiera mejorar aún más, entonces tomamos nuestro Roast Beef, lo cubrimos con salsa de queso Cheddar y el sabroso aderezo Red Ranch y lo servimos en un pan con cebolla tostada, entonces dijimos, 'quedó perfecto'.",
                calories_description: "450 Calorías | 900-1260 Combo",
                type: 1, // keep it false if the product should not show the type or "1" for classic, "2" for double and "3" for half pound
                image: require("~/assets/images/classic-beef-n-cheddar.jpg"),
            },
            {
                name: "double beef & cheddar",
                subTitle: false,
                slug: "double-beef-n-cheddar",
                calories: 630,
                description: "¿Cómo mejoras algo que ya es perfecto? muy fácil; lo haces más grande. El Double Beef & Cheddar de Arby’s ofrece el doble de Roast Beef que el Classic Beef & Cheddar. Esta fue una gran noticia para aquellas personas que estaban cansadas de comprar dos Classic Beef & Cheddar para luego pasar todo el Roast Beef, la salsa de queso Cheddar y el Red Ranch a un solo pan de cebolla.",
                calories_description: "630 Calorías | 1080-1440 Combo",
                type: 2,
                image: require("~/assets/images/double-beef-n-cheddar.jpg"),
            },
            {
                name: "HALF POUND BEEF & CHEDDAR",
                subTitle: false,
                slug: "half-pound-beef-n-cheddar",
                calories: 740,
                description: "Solo para carnívoros; media libra del famoso Roast Beef de Arby's, cortado finamente y servido calientito en pan de cebolla, acompañado de salsa de queso Cheddar y aderezo Red Ranch.",
                calories_description: "750 Calorías | 1190-1550 Combo",
                type: 3,
                image: require("~/assets/images/half-pound-beef-n-cheddar.jpg"),
            },
            {
                name: "Deluxe Beef & Cheddar",
                subTitle: false,
                slug: "deluxe-beef-n-cheddar",
                calories: 460,
                description: "Nuestro famoso Roast Beef calientito y cortado finamente, servido en un pan de cebolla con salsa de queso Cheddar, aderezo Red Ranch, pero le agregamos tomate fresco, lechuga y cebolla morada para hacerlo aún más sabroso.",
                calories_description: "460 Calorías | 910-1270 Combo",
                type: 1,
                image: require("~/assets/images/deluxe-beef-n-cheddar.jpg"),
            },
            {
                name: "double Deluxe Beef & Cheddar",
                subTitle: false,
                slug: "double-deluxe-beef-n-cheddar",
                calories: 640,
                description: "Siempre habrá quien quiere más Roast Beef; con el doble de Roast Beef y el doble de salsa de queso Cheddar, todo servido en pan de cebolla tostada, aderezo Red Ranch, tomate, lechuga y cebolla morada.",
                calories_description: "640 Calorías | 1090-1450 Combo",
                type: 2,
                image: require("~/assets/images/double-deluxe-beef-n-cheddar.jpg"),
            },
            {
                name: "half pound Deluxe Beef & Cheddar",
                subTitle: false,
                slug: "half-pound-deluxe-beef-n-cheddar",
                calories: 750,
                description: "Ponemos media libra del Roast Beef favorito de todos en este Half Pound Beef & Cheddar. Sin embargo, eso no incluye el peso de las otras cosas, pero estamos seguros de que el pan de cebolla, la salsa de queso cheddar, el Red Ranch, tomate, lechuga y cebolla morada; hacen que sobrepase media libra.",
                calories_description: "750 Calorías | 1190-1550 Combo",
                type: 3,
                image: require("~/assets/images/half-pound-deluxe-beef-n-cheddar.jpg"),
            },
        ],
    },
    {
        title: "Slow Smoked Beef brisket",
        sectionId: "",
        products: [{
                name: "Smokehouse Beef Brisket",
                subTitle: false,
                slug: "smokehouse-beef-brisket",
                calories: 360,
                description: "Nuestra deliciosa carne Brisket ahumada pacientemente por más de 13 horas, cortada y servida calientita en un pan artesanal, con queso Gouda derretido, cebolla morada, tomate fresco, lechuga y mayonesa. Una joya de Arby’s.",
                calories_description: "360 Calorías | 810-1170 Combo",
                type: false,
                image: require("~/assets/images/smokehouse-beef-brisket.jpg"),
            },
            {
                name: "Deluxe Smokehouse Beef Brisket",
                subTitle: false,
                slug: "deluxe-smokehouse-beef-brisket",
                calories: 690,
                description: "Nos propusimos hacer un sándwich con capas de sabor ahumado y este fue el resultado. Nuestro Brisket se ahúma durante al menos 13 horas. Cubrimos esa deliciosa carne ahumada con queso Gouda, cebollas crujientes, mayonesa y salsa BBQ y lo servimos todo en un pan estilo artesanal.",
                calories_description: "690 Calorías | 1140-1500 Calorías ",
                type: false,
                image: require("~/assets/images/deluxe-smokehouse-beef-brisket.jpg"),
            },
        ],
    },
    {
        title: "Sweet & Smoked Pork",
        sectionId: "pork",
        products: [{
                name: "pulled pork",
                subTitle: false,
                slug: "pulled-pork",
                calories: 560,
                description: "Deliciosa y calientita carne de cerdo desmenuzada con rico sabor BBQ, servida en un pan brioche ligeramente tostado con queso manchego derretido, acompañada con cebolla crujiente, tomate fresco, lechuga y mayonesa.",
                calories_description: "560 Calorías | 1010-1370 Combo",
                type: false,
                image: require("~/assets/images/pulled-pork.jpg"),
            },
            {
                name: "Triple Thick BLT",
                subTitle: false,
                slug: "triple-thick-blt",
                calories: 540,
                description: "Una fabulosa combinación de carne y vegetales frescos; crujiente bacon bañado en azúcar morena, con mayonesa, lechuga y tomate fresco en pan brioche.",
                calories_description: "540 Calorías | 990-1350 Combo",
                type: false,
                image: require("~/assets/images/triple-thick-blt.jpg"),
            },
        ],
    },
    {
        title: "Turkey",
        sectionId: "turkey",
        products: [{
                name: "Triple Cheese Turkey BLT",
                subTitle: false,
                slug: "triple-cheese-turkey-blt",
                calories: 780,
                description: "Para amantes del queso. Tibias rebanadas de pechuga de pavo con tres quesos derretidos; manchego, cheddar y gouda, complementados con bacon, tomate, lechuga y mayonesa, servido en pan de cebolla.",
                calories_description: "780 Calorías | 1230-1590 Combo",
                type: false,
                image: require("~/assets/images/triple-cheese-turkey-blt.jpg"),
            },
            {
                name: "Turkey Avocado Bacon Club",
                subTitle: false,
                slug: "turkey-avocado-bacon-club",
                calories: 730,
                description: "Pechuga de pavo en pan integral con miel, crema de aguacate, bacon, queso suizo derretido, lechuga, tomate fresco, cebolla morada y mayonesa.",
                calories_description: "730 Calorías | 1180-1540 Combo",
                type: false,
                image: require("~/assets/images/turkey-avocado-bacon-club.jpg"),
            },
            {
                name: "Roast Turkey & Swiss",
                subTitle: false,
                slug: "roast-turkey-n-swiss",
                calories: 720,
                description: "Pechuga de pavo asada en pan de trigo integral y miel o Wrap artesanal, queso suizo, mayonesa, mostaza picante, lechuga, tomate fresco y cebolla morada.",
                calories_description: "720 Calorías | 1170-1530 Combo",
                type: false,
                image: require("~/assets/images/roast-turkey-n-swiss.jpg"),
            },
            {
                name: "Roast Turkey Ranch & Bacon",
                subTitle: false,
                slug: "roast-turkey-ranch-n-bacon",
                calories: 810,
                description: "El Roast Turkey Ranch & Bacon Sandwich viene con pavo asado al estilo deli, queso suizo, mayonesa, mostaza picante, lechuga, tomate fresco y cebolla morada, todo en medio de dos panes de trigo y miel. Intentamos agregar esos ingredientes al nombre, pero “Roast Turkey Ranch & Bacon en Pan de Trigo y Miel” sería un nombre muy largo ridículo para este sándwich.",
                calories_description: "810 Calorías | 1260-1620 Combo",
                type: false,
                image: require("~/assets/images/roast-turkey-ranch-n-bacon.jpg"),
            },
        ],
    },
    {
        title: "roasted chicken",
        sectionId: "chicken",
        products: [{
                name: "Classic Roasted Chicken",
                subTitle: false,
                slug: "classic-roasted-chicken",
                calories: 370,
                description: "Si te apetece un pollo jugoso y asado a fuego lento, cubierto con tomates, lechuga y mayonesa, todo en pan artesanal, entonces este sería un buen momento para apresurarte y visitar Arby’s.",
                calories_description: "370 Calorías | 820-1180 Combo",
                type: false,
                image: require("~/assets/images/classic-roasted-chicken.jpg"),
            },
            {
                name: "CHICKEN BACON SWISS",
                subTitle: false,
                slug: "chicken-bacon-swiss",
                calories: 610,
                description: "Prueba el sándwich más sabroso de Arby’s hasta la fecha: pollo asado a fuego lento, crujiente bacon, queso suizo derretido y aderezo Honey Mustard. Sabemos que volverás por otro.",
                calories_description: "610 Calorías | 1060-1420 Combo",
                type: false,
                image: require("~/assets/images/chicken-bacon-swiss.jpg"),
            },
            {
                name: "Chicken Club Wrap",
                subTitle: false,
                slug: "chicken-club-wrap",
                calories: 650,
                description: "Es difícil elegir un ingrediente favorito en este Wrap. Para algunos, es el pollo asado, el bacon o el queso cheddar. Para otros, es la cebolla morada, los tomates frescos, el aderezo honey mustard o el wrap artesanal, y para una que otra persona, es la lechuga.",
                calories_description: "650 Calorías | 1100-1460 Combo",
                type: false,
                image: require("~/assets/images/chicken-club-wrap.jpg"),
            },
        ],
    },
    {
        title: "crispy chicken",
        sectionId: "",
        products: [{
                name: "Classic Crispy Chicken",
                subTitle: false,
                slug: "classic-crispy-chicken",
                calories: 510,
                description: "Una pechuga de pollo crujiente, mayonesa y tomate fresco; todo en un pan artesanal ligeramente tostado. Simple, pero sabroso.",
                calories_description: "510 Calorías | 960-1320 Combo",
                type: false,
                image: require("~/assets/images/classic-crispy-chicken.jpg"),
            },
            {
                name: "Crispy Chicken Bacon Swiss",
                subTitle: false,
                slug: "crispy-chicken-bacon-swiss",
                calories: 610,
                description: "Pechuga de pollo perfectamente crujiente y cubierta con bacon, queso suizo derretido, lechuga, tomate y salsa Honey Mustard. Servido en un pan artesanal ligeramente tostado. Tu sentido del gusto te agradecerá tu generosidad.",
                calories_description: "610 Calorías | 1060-1420 Combo",
                type: false,
                image: require("~/assets/images/crispy-chicken-bacon-swiss.jpg"),
            },
            {
                name: "Crispy Chicken & Cheese",
                subTitle: false,
                slug: "crispy-chicken-n-cheese",
                calories: 610,
                description: "Un pan artesanal de arriba abajo, te preguntarás ¿y qué hay en medio? Oh, un crujiente filete de pechuga de pollo, con queso Mozzarella derretido, tomate fresco y lechuga, seguro que te gustará.",
                calories_description: "610 Calorías | 910-1270 Combo",
                type: false,
                image: require("~/assets/images/crispy-chicken-n-cheese.jpg"),
            },
            {
                name: "Chicken Tenders",
                subTitle: false,
                slug: "chicken-tenders",
                nutrations: [{
                        piezas: 3,
                        "Calorías": 370,
                    },
                    {
                        piezas: 5,
                        "Calorías": 610,
                    },
                ],
                description: "Tiernas tiras de pechuga de pollo empanado que son memorables, acompañados con cualquiera de nuestras famosas salsas.",
                calories_description: "3 piezas 370 Calorías | 820-1180 Combo - 5 piezas 610 Calorías | 1060-1420 Combo",
                type: false,
                image: require("~/assets/images/chicken-tenders.jpg"),
            },
        ],
    },
    {
        title: "Acompañantes",
        sectionId: "acompanantes",
        products: [{
                name: "Loaded Curly Fries",
                subTitle: false,
                slug: "loaded-curly-fries",
                calories: 670,
                description: "Un plato de papas curly con queso cheddar rallado, salsa de queso cheddar, aderezo Parmesan Peppercorn Ranch y crujiente bacon. Nada más que decir.",
                calories_description: "670 Calorías",
                type: false,
                image: require("~/assets/images/loaded-curly-fries.jpg"),
            },
            {
                name: "curly fries",
                subTitle: false,
                slug: "curly-fries",
                calories: "S 410 | M 550 | L 650",
                description: "Deliciosas papas en espiral, crujientes y perfectamente sazonadas; son deliciosas por sí solas y son aún mejores con alguna de nuestras famosas salsas.",
                calories_description: "S 410 | M 550 | L 650 Calorías",
                type: false,
                image: require("~/assets/images/curly-fries.jpg"),
            },
            // {
            //     name: "Onion Rings",
            //     subTitle: false,
            //     slug: "onion-rings",
            //     nutrations: [{ piezas: 2, "Calorías": 420 }],
            //     description: "Crujientes aros de cebolla de corte grueso, necesitarás tus dos manos para disfrutarlos.",
            //     calories_description: "(5 piezas) 420 Calorías",
            //     type: false,
            //     image: require("~/assets/images/onion-rings.jpg"),
            // },
            {
                name: "Potato cakes",
                subTitle: false,
                slug: "potato-cakes.jpg",
                nutrations: [
                    { piezas: 2, "Calorías": 250 },
                    { piezas: 3, "Calorías": 370 },
                    { piezas: 4, "Calorías": 490 },
                ],
                description: "Papas desmenuzadas en finos trozos y fritas a la perfección.",
                calories_description: "(2 piezas) 250 Calorías | (3 piezas) 370 Calorías | (4 piezas) 490 Calorías",
                type: false,
                image: require("~/assets/images/potato-cakes.jpg"),
            },
            {
                name: "side salad",
                subTitle: false,
                slug: "side-salad",
                calories: 80,
                description: "Un complemento ligero para quienes prefieren opciones con menos calorías.",
                calories_description: "80 Calorías",
                type: false,
                image: require("~/assets/images/side-salad.jpg"),
            },
            {
                name: "Mozzarella Sticks",
                subTitle: false,
                slug: "mozzarella-sticks",
                nutrations: [
                    { piezas: 4, "Calorías": 440 },
                    { piezas: 6, "Calorías": 650 },
                ],
                description: "Exquisitos dedos de queso mozzarella, crujientes por fuera y derretidos por dentro, servidos con salsa marinara.",
                calories_description: "(4 piezas) 440 Calorías | (6 piezas) 650 Calorías",
                type: false,
                image: require("~/assets/images/mozzarella-sticks.jpg"),
            },
        ],
    },
    {
        title: "batidas",
        sectionId: "batidas",
        products: [{
                name: "Jamocha",
                subTitle: false,
                slug: "jamocha",
                calories: "S 590 | M 830 | L 1060",
                description: "Es incuestionable que el chocolate y el café combinan perfecto, y es verdad que los seres humanos amamos las batidas, tomamos estas dos realidades y creamos nuestra famosa batida Jamocha, sabe a café, sabe a chocolate y es uno de los favoritos característicos de Arby's.",
                calories_description: "S 590 | M 830 | L 1060 Calorías",
                type: false,
                image: require("~/assets/images/jamocha.jpg"),
            },
            {
                name: "Chocolate",
                subTitle: false,
                slug: "chocolate",
                calories: "S 590 | M 830 | L 1050",
                description: "Una deliciosa batida de chocolate hecha con chocolate Ghirardelli premium y rociado con más chocolate Ghirardelli premium. Lo que significa que en Arby's esta es una batida premium.",
                calories_description: "S 590 | M 830 | L 1050 Calorías",
                type: false,
                image: require("~/assets/images/chocolate.jpg"),
            },
            {
                name: "Vainilla",
                subTitle: false,
                slug: "vainilla",
                calories: "S 490 | M 690 | L 900",
                description: "¿Te gusta mantener las cosas simples y sin complicaciones? ¿Sabes lo que te gusta y porqué te gusta? Entonces nuestra batida de vainilla es para ti.",
                calories_description: "S 490 | M 690 | L 900 Calorías",
                type: false,
                image: require("~/assets/images/vainilla.jpg"),
            },
        ],
    },
    {
        title: "postres",
        sectionId: "",
        products: [
            // {
            //     name: "Triple Chocolate",
            //     subTitle: false,
            //     slug: "triple-chocolate",
            //     calories: 450,
            //     description: "Galletas calientitas horneadas con triple chocolate Ghirardelli. Un dulce final a tu antojo después de satisfacer tu apetito de carne en Arby’s.",
            //     calories_description: "450 Calorías",
            //     type: false,
            //     image: require("~/assets/images/triple-chocolate.jpg"),
            // },
            {
                name: "Salted Caramel",
                subTitle: false,
                slug: "salted-caramel",
                calories: 430,
                description: "Galletas de caramelo y chocolate Ghirardelli con un toque salado, ¿salado?, así es; tan raro como suena es tan rico como sabe.",
                calories_description: "430 Calorías",
                type: false,
                image: require("~/assets/images/salted-caramel.jpg"),
            },
            {
                name: "Cherry turnover",
                subTitle: false,
                slug: "cherry-turnover",
                calories: 430,
                description: "Una vez que has disfrutado de un sándwich de carne, la reacción natural de tu cuerpo es querer un postre. Si eres del tipo de persona que gusta de los dulces con sabor a fruta, te encantará nuestro Turnover de cherry, crujiente y con un dulce relleno de cherry.",
                calories_description: "430 Calorías",
                type: false,
                image: require("~/assets/images/cherry-turnover.jpg"),
            },
            {
                name: "Apple turnover",
                subTitle: false,
                slug: "apple-turnover",
                calories: 390,
                description: "Todos saben que comer una manzana al día te mantiene saludable, pero ¿sabías que comer un Turnover de manzana al día te ayuda a vivir más?, quien lo come vive más feliz, más contento y satisfecho.",
                calories_description: "390 Calorías",
                type: false,
                image: require("~/assets/images/apple-turnover.jpg"),
            },
            {
                name: "quesito",
                subTitle: false,
                slug: "quesito",
                calories: 340,
                description: "Hay quien daría lo que fuera por uno de nuestros Quesitos; tan rico, tan crujiente, delicioso y relleno de delicioso queso crema que te dejará con ganas de otro.",
                calories_description: "340 Calorías",
                type: false,
                image: require("~/assets/images/quesito.jpg"),
            },
        ],
    },
    {
        title: "Bebidas",
        sectionId: "",
        products: [{
                name: "Coca-Cola",
                subTitle: false,
                slug: "coca-cola",
                calories: 160,
                description: "",
                calories_description: "160 Calorías",
                type: false,
                image: require("~/assets/images/coca-cola.jpg"),
            },
            {
                name: "Coca Cola Zero Sugar",
                subTitle: false,
                slug: "coca-cola-zero-sugar",
                calories: 0,
                description: "",
                calories_description: "0 Calorías",
                type: false,
                image: require("~/assets/images/coca-cola-zero-sugar.jpg"),
            },
            {
                name: "Diet Coke",
                subTitle: false,
                slug: "diet-coke",
                calories: 0,
                description: "",
                calories_description: "0 Calorías",
                type: false,
                image: require("~/assets/images/diet-coke.jpg"),
            },
            {
                name: "Sprite",
                subTitle: false,
                slug: "sprite",
                calories: 160,
                description: "",
                calories_description: "160 Calorías",
                type: false,
                image: require("~/assets/images/sprite.jpg"),
            },
            {
                name: "HI-C Fruit Punch",
                subTitle: false,
                slug: "hi-c-fruit-punch",
                calories: 170,
                description: "",
                calories_description: "170 Calorías",
                type: false,
                image: require("~/assets/images/hi-c-fruit-punch.jpg"),
            },
            {
                name: "Fanta",
                subTitle: false,
                slug: "fanta",
                calories: 170,
                description: "",
                calories_description: "170 Calorías",
                type: false,
                image: require("~/assets/images/fanta.jpg"),
            },
        ],
    },
    {
        title: "desayuno",
        subtitle: "(HASTA LAS 10:30 AM)",
        sectionId: "desayuno",
        products: [{
                name: "Roast Beef Breakfast Sandwich",
                subTitle: false,
                slug: "roast-beef-breakfast-sandwich",
                calories: 560,
                description: "Un sándwich al estilo único de Arby’s®. Delicioso roast beef con jamón o bacon, queso cheddar y huevo en pan brioche.",
                calories_description: "560 Calorías",
                type: false,
                image: require("~/assets/images/roast-beef-breakfast-sandwich.jpg"),
            },
            {
                name: "Sandwich de Jamón o Bacon",
                subTitle: false,
                slug: "sandwich-de-jamon-o-bacon",
                calories: 840,
                description: "El clásico pan sobao de Puerto Rico, con jamón o bacon, queso cheddar derretido y huevo. La mejor manera de comenzar tu día.",
                calories_description: "840 Calorías | Combo 1090-1310",
                type: false,
                image: require("~/assets/images/sandwich-de-jamon-o-bacon.jpg"),
            },
            {
                name: "Avocado Sandwich Jamón o Bacon y queso suizo",
                subTitle: false,
                slug: "avocado-sandwich-jamon-o-bacon-y-queso-suizo",
                calories: 810,
                description: "Una fusión de sabores de Puerto Rico por la mañana; jamón o bacon en pan sobao, queso suizo derretido, aguacate, mayonesa y huevo.",
                calories_description: "810 Calorías | Combo 1060-1280 ",
                type: false,
                image: require("~/assets/images/avocado-sandwich-jamon-o-bacon-y-queso-suizo.jpg"),
            },
            {
                name: "Criollo Sandwich",
                subTitle: false,
                slug: "criollo-sandwich",
                calories: 820,
                description: "De Puerto Rico para el mundo; jamón y bacon en un pan criollo, queso mozzarella derretido, mayonesa y huevo.",
                calories_description: "820 Calorías | Combo 1070-1290",
                type: false,
                image: require("~/assets/images/criollo-sandwich.jpg"),
            },
            {
                name: "Tostadas con Mantequilla",
                subTitle: false,
                slug: "tostadas-con-mantequilla",
                calories: 470,
                description: "Pan criollo tostado con mantequilla. Un clásico mañanero.",
                calories_description: "470 Calorías | 720 -940 Combo",
                type: false,
                image: require("~/assets/images/tostadas-con-mantequilla.jpg"),
            },
            {
                name: "Tostadas con Queso",
                subTitle: false,
                slug: "tostadas-con-queso",
                calories: 700,
                description: "Pan criollo tostado con queso y mantequilla. Un clásico mañanero.",
                calories_description: "700 Calorías | 950-1170 Combo ",
                type: false,
                image: require("~/assets/images/tostadas-con-queso.jpg"),
            },
            {
                name: "Revoltillo al Plato",
                subTitle: "(Escoge entre Jamón o Bacon)",
                slug: "revoltillo-al-plato`",
                calories: "160 - 200",
                description: "Un plato completo para el desayuno; huevo batido con jamón o bacon, un potato cake, tostadas, café o jugo.",
                calories_description: "160 - 200 Calorías | 1,265 - 1,485 Combo",
                type: false,
                image: require("~/assets/images/revoltillo-al-plato.jpg"),
            },
            {
                name: "Revoltillo deluxe al plato",
                subTitle: "(Escoge entre Jamón o Bacon)",
                slug: "revoltillo-deluxe-al-plato",
                calories: "180 - 200",
                description: "Huevo batido con tomate y cebolla, un potato cake, tostadas, jamón o bacon y café o jugo.",
                calories_description: "180 - 220 Calorías | 1,275 - 1,495 Combo",
                type: false,
                image: require("~/assets/images/revoltillo-deluxe-al-plato.jpg"),
            },
            {
                name: "Pancakes con Maple Syrup",
                subTitle: false,
                slug: "pancakes-con-maple-syrup",
                calories: 560,
                description: "Tres esponjosos pancakes hechos al momento. Eleva su sabor con un chorrito de dulce maple syrup.",
                calories_description: "560 Calorías",
                type: false,
                image: require("~/assets/images/pancakes-con-maple-syrup.jpg"),
            },
            {
                name: "Avena Quaker®",
                subTitle: false,
                slug: "avena-quaker",
                calories: 300,
                description: "Calientita avena Quaker® preparada al momento todas las mañanas. ¿Qué mejor manera de comenzar tus mañanas?",
                calories_description: "300 Calorías",
                type: false,
                image: require("~/assets/images/avena-quaker.jpg"),
            },
            {
                name: "Café negro",
                subTitle: false,
                slug: "cafe-negro",
                calories: 0,
                description: "",
                calories_description: "0 Calorías",
                type: false,
                image: require("~/assets/images/cafe-negro.jpg"),
            },
            {
                name: "Café espresso con leche",
                subTitle: false,
                slug: "cafe-expresso-con-leche",
                calories: 50,
                description: "",
                calories_description: "50 Calorías",
                type: false,
                image: require("~/assets/images/otros-cafes.jpg"),
            },
            {
                name: "Cappuccino",
                subTitle: false,
                slug: "cappuccino",
                calories: 70,
                description: "",
                calories_description: "70 Calorías",
                type: false,
                image: require("~/assets/images/otros-cafes.jpg"),
            },
            {
                name: "Mochaccino",
                subTitle: false,
                slug: "mochaccino",
                calories: 130,
                description: "",
                calories_description: "130 Calorías",
                type: false,
                image: require("~/assets/images/otros-cafes.jpg"),
            },
            {
                name: "Chocolate Caliente",
                subTitle: false,
                slug: "chocolate-caliente",
                calories: 220,
                description: "",
                calories_description: "220 Calorías",
                type: false,
                image: require("~/assets/images/otros-cafes.jpg"),
            },
            {
                name: "French vanilla",
                subTitle: false,
                slug: "french-vanilla",
                calories: 130,
                description: "",
                calories_description: "130 Calorías",
                type: false,
                image: require("~/assets/images/otros-cafes.jpg"),
            },
            {
                name: "Café Cortadito",
                subTitle: false,
                slug: "cafe-cortadito",
                calories: 15,
                description: "",
                calories_description: "15 Calorías",
                type: false,
                image: require("~/assets/images/otros-cafes.jpg"),
            },
            {
                name: "Cappuccino vainilla",
                subTitle: false,
                slug: "cappuccino-vainilla",
                calories: 190,
                description: "",
                calories_description: "190 Calorías",
                type: false,
                image: require("~/assets/images/otros-cafes.jpg"),
            },
            {
                name: "Choco vainilla",
                subTitle: false,
                slug: "choco-vainilla",
                calories: 220,
                description: "",
                calories_description: "220 Calorías",
                type: false,
                image: require("~/assets/images/otros-cafes.jpg"),
            },
            {
                name: "Doble espresso americano",
                subTitle: false,
                slug: "doble-expresso-americano",
                calories: 0,
                description: "",
                calories_description: "0 Calorías",
                type: false,
                image: require("~/assets/images/otros-cafes.jpg"),
            },
        ],
    },
    //
];

const menuDeNinos = [{
        title: "PLATO PRINCIPAL",
        sectionId: "",
        products: [{
                name: "2 CHICKEN TENDERS",
                subTitle: false,
                slug: "2-chicken-tenders",
                calories: 240,
                description: "",
                calories_description: "240 Calorías | Combo 890 - 1080",
                type: false,
                // image: require("~/assets/images/grilled-cheese.jpg"),
                image: require("~/assets/images/2-chicken-tenders.jpg"),
            },
            {
                name: "GRILLED CHEESE",
                subTitle: false,
                slug: "grilled-cheese",
                calories: 730,
                description: "",
                calories_description: "730 Calorías | Combo 730 - 820",
                type: false,
                image: require("~/assets/images/grilled-cheese.jpg"),
            },
            {
                name: "MOZZARELLA CHEESE STICKS",
                subTitle: false,
                slug: "mozzarella-cheese-sticks",
                calories: 440,
                description: "",
                calories_description: "440 Calorías | Combo 650 - 840",
                type: false,
                image: require("~/assets/images/mozzarella-sticks.jpg"),
            },
        ],
    },
    {
        title: "Acompañantes",
        sectionId: "",
        products: [{
            name: "Kids Curly Fries",
            subTitle: false,
            slug: "kids-curly-fries",
            calories: 250,
            description: "",
            calories_description: "250 Calorías",
            type: false,
            image: require("~/assets/images/curly-fries.jpg"),
        }, ],
    },
    {
        title: "Bebidas",
        sectionId: "",
        products: [{
                name: "JUGO DE CHINA",
                subTitle: false,
                slug: "jugo-de-china",
                calories: 110,
                description: "",
                calories_description: "110 Calorías",
                type: false,
                image: require("~/assets/images/jugo-de-china.jpg"),
            }, {
                name: "JUGO DE MANZANA",
                subTitle: false,
                slug: "jugo-de-manzana",
                calories: 150,
                description: "",
                calories_description: "150 Calorías",
                type: false,
                image: require("~/assets/images/jugo-de-manzana.jpg"),
            },
            {
                name: "JUGO DE UVA",
                subTitle: false,
                slug: "jugo-de-uva",
                calories: 130,
                description: "",
                calories_description: "130 Calorías",
                type: false,
                image: require("~/assets/images/jugo-de-uva.jpg"),
            },
            {
                name: "KIDS SODA",
                subTitle: false,
                slug: "kids-soda",
                calories: "0-190",
                description: "",
                calories_description: "0-190 Calorías",
                type: false,
                image: require("~/assets/images/coca-cola.jpg"),
            },
            {
                name: "JUGO DE CRANBERRY",
                subTitle: false,
                slug: "jugo-de-cranberry",
                calories: 150,
                description: "",
                calories_description: "150 Calorías",
                type: false,
                image: require("~/assets/images/jugo-de-cranberry.jpg"),
            },
            {
                name: "BATIDA DE 12OZ",
                subTitle: false,
                slug: "batida-de-12oz",
                calories: "280 - 350",
                description: "",
                calories_description: "280 - 350 Calorías",
                type: false,
                image: require("~/assets/images/batida-de-12oz.jpg"),
            },
        ],
    },
];

export {
    menuDeNinos,
    menu
}